# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"

    filter_sets:
        article_front_image:
            quality: 75
            filters:
                thumbnail:
                    size: [ 416, 260 ]
                    mode: outbond
        product_image_card:
            quality: 75
            filters:
                thumbnail:
                    size: [ 320, 320 ]
                    mode: outbond
                watermark_image:
                    # path to the watermark file (prepended with "%kernel.project_dir%")
                    image: assets/styles/images/png/favicon.png
                    # size of the water mark relative to the input image
                    size: 0.2
                    # set the position of the watermark
                    position: bottom
        product_image_cart:
            quality: 75
            filters:
                thumbnail:
                    size: [ 60, 60 ]
                    mode: outbond
        avatar_image:
            quality: 75
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: outbond
        avatar_front:
            quality: 75
            filters:
                thumbnail:
                    size: [106, 106]
                    mode: outbond
        logostruct_image:
            quality: 75
            filters:
                thumbnail:
                    size: [ 286, 180 ]
                    mode: outbond
        illustration_structure:
            quality: 75
            filters:
                thumbnail:
                    size: [ 398, 238 ]
                    mode: outbond
                background :
                    size : [404, 244]
                    position : center
                    color : '#cdb55f'
        prez_event:
            quality: 150
            filters:
                thumbnail:
                    size: [ 800, 500 ]
                    mode: outbond
        history_event:
            quality: 150
            filters:
                thumbnail:
                    size: [ 194, 130 ]
                    mode: outbond
